
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.VBox vbox2;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Label label1;
	private global::Gtk.Entry entryUsername;
	private global::Gtk.HBox hbox3;
	private global::Gtk.Label label2;
	private global::Gtk.Entry entryPassword;
	private global::Gtk.HBox hbox4;
	private global::Gtk.Label label3;
	private global::Gtk.Entry entryIP;
	private global::Gtk.VBox vbox4;
	private global::Gtk.HBox hbox62;
	private global::Gtk.VBox vbox8;
	private global::Gtk.VBox vbox7;
	private global::Gtk.RadioButton radiobuttonDelegation;
	private global::Gtk.RadioButton radiobuttonDetails;
	private global::Gtk.VBox vbox6;
	private global::Gtk.RadioButton radiobuttonCreate;
	private global::Gtk.RadioButton radiobuttonDelete;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView textviewHostnames;
	private global::Gtk.VBox vbox5;
	private global::Gtk.Label label7;
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	private global::Gtk.TextView textviewAPIReturn;
	private global::Gtk.HBox hbox19;
	private global::Gtk.Button buttonPark;
	private global::Gtk.Button buttonClear;
	private global::Gtk.HButtonBox hbuttonbox2;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MassDNS");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(6));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Username:");
		this.hbox2.Add (this.label1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.entryUsername = new global::Gtk.Entry ();
		this.entryUsername.CanFocus = true;
		this.entryUsername.Name = "entryUsername";
		this.entryUsername.IsEditable = true;
		this.entryUsername.InvisibleChar = '●';
		this.hbox2.Add (this.entryUsername);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.entryUsername]));
		w2.Position = 1;
		this.vbox2.Add (this.hbox2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Password:");
		this.hbox3.Add (this.label2);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label2]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.entryPassword = new global::Gtk.Entry ();
		this.entryPassword.CanFocus = true;
		this.entryPassword.Name = "entryPassword";
		this.entryPassword.IsEditable = true;
		this.entryPassword.Visibility = false;
		this.entryPassword.InvisibleChar = '●';
		this.hbox3.Add (this.entryPassword);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.entryPassword]));
		w5.Position = 1;
		this.vbox2.Add (this.hbox3);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("IP:");
		this.hbox4.Add (this.label3);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label3]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.entryIP = new global::Gtk.Entry ();
		this.entryIP.CanFocus = true;
		this.entryIP.Name = "entryIP";
		this.entryIP.IsEditable = true;
		this.entryIP.InvisibleChar = '●';
		this.hbox4.Add (this.entryIP);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.entryIP]));
		w8.Position = 1;
		this.vbox2.Add (this.hbox4);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox4]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		this.vbox1.Add (this.vbox2);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox2]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox62 = new global::Gtk.HBox ();
		this.hbox62.Name = "hbox62";
		this.hbox62.Spacing = 6;
		// Container child hbox62.Gtk.Box+BoxChild
		this.vbox8 = new global::Gtk.VBox ();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		this.hbox62.Add (this.vbox8);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox62 [this.vbox8]));
		w11.Position = 0;
		// Container child hbox62.Gtk.Box+BoxChild
		this.vbox7 = new global::Gtk.VBox ();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.radiobuttonDelegation = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Delegation"));
		this.radiobuttonDelegation.CanFocus = true;
		this.radiobuttonDelegation.Name = "radiobuttonDelegation";
		this.radiobuttonDelegation.DrawIndicator = true;
		this.radiobuttonDelegation.UseUnderline = true;
		this.radiobuttonDelegation.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.vbox7.Add (this.radiobuttonDelegation);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.radiobuttonDelegation]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.radiobuttonDetails = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Details"));
		this.radiobuttonDetails.CanFocus = true;
		this.radiobuttonDetails.Name = "radiobuttonDetails";
		this.radiobuttonDetails.DrawIndicator = true;
		this.radiobuttonDetails.UseUnderline = true;
		this.radiobuttonDetails.Group = this.radiobuttonDelegation.Group;
		this.vbox7.Add (this.radiobuttonDetails);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.radiobuttonDetails]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		this.hbox62.Add (this.vbox7);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox62 [this.vbox7]));
		w14.Position = 1;
		// Container child hbox62.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.radiobuttonCreate = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Create"));
		this.radiobuttonCreate.CanFocus = true;
		this.radiobuttonCreate.Name = "radiobuttonCreate";
		this.radiobuttonCreate.DrawIndicator = true;
		this.radiobuttonCreate.UseUnderline = true;
		this.radiobuttonCreate.Group = this.radiobuttonDelegation.Group;
		this.vbox6.Add (this.radiobuttonCreate);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.radiobuttonCreate]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.radiobuttonDelete = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Delete"));
		this.radiobuttonDelete.CanFocus = true;
		this.radiobuttonDelete.Name = "radiobuttonDelete";
		this.radiobuttonDelete.DrawIndicator = true;
		this.radiobuttonDelete.UseUnderline = true;
		this.radiobuttonDelete.Group = this.radiobuttonDelegation.Group;
		this.vbox6.Add (this.radiobuttonDelete);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.radiobuttonDelete]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		this.hbox62.Add (this.vbox6);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox62 [this.vbox6]));
		w17.Position = 2;
		this.vbox4.Add (this.hbox62);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox62]));
		w18.Position = 0;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textviewHostnames = new global::Gtk.TextView ();
		this.textviewHostnames.Buffer.Text = "Input Hostnames on new lines";
		this.textviewHostnames.CanFocus = true;
		this.textviewHostnames.Name = "textviewHostnames";
		this.GtkScrolledWindow.Add (this.textviewHostnames);
		this.vbox4.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.GtkScrolledWindow]));
		w20.Position = 1;
		this.vbox1.Add (this.vbox4);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox4]));
		w21.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Returned from API");
		this.vbox5.Add (this.label7);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.label7]));
		w22.Position = 0;
		w22.Expand = false;
		w22.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.textviewAPIReturn = new global::Gtk.TextView ();
		this.textviewAPIReturn.CanFocus = true;
		this.textviewAPIReturn.Name = "textviewAPIReturn";
		this.textviewAPIReturn.Editable = false;
		this.GtkScrolledWindow1.Add (this.textviewAPIReturn);
		this.vbox5.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.GtkScrolledWindow1]));
		w24.Position = 1;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox19 = new global::Gtk.HBox ();
		this.hbox19.Name = "hbox19";
		this.hbox19.Spacing = 6;
		// Container child hbox19.Gtk.Box+BoxChild
		this.buttonPark = new global::Gtk.Button ();
		this.buttonPark.CanFocus = true;
		this.buttonPark.Name = "buttonPark";
		this.buttonPark.UseUnderline = true;
		this.buttonPark.Label = global::Mono.Unix.Catalog.GetString ("Do Things");
		this.hbox19.Add (this.buttonPark);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.buttonPark]));
		w25.Position = 0;
		w25.Expand = false;
		w25.Fill = false;
		// Container child hbox19.Gtk.Box+BoxChild
		this.buttonClear = new global::Gtk.Button ();
		this.buttonClear.CanFocus = true;
		this.buttonClear.Name = "buttonClear";
		this.buttonClear.UseUnderline = true;
		this.buttonClear.Label = global::Mono.Unix.Catalog.GetString ("Clear");
		this.hbox19.Add (this.buttonClear);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.buttonClear]));
		w26.Position = 1;
		w26.Expand = false;
		w26.Fill = false;
		// Container child hbox19.Gtk.Box+BoxChild
		this.hbuttonbox2 = new global::Gtk.HButtonBox ();
		this.hbuttonbox2.Name = "hbuttonbox2";
		this.hbox19.Add (this.hbuttonbox2);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.hbuttonbox2]));
		w27.Position = 2;
		this.vbox5.Add (this.hbox19);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox19]));
		w28.Position = 2;
		w28.Expand = false;
		w28.Fill = false;
		this.vbox1.Add (this.vbox5);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox5]));
		w29.Position = 2;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 500;
		this.DefaultHeight = 477;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.buttonPark.Clicked += new global::System.EventHandler (this.buttonClickedPark);
		this.buttonClear.Clicked += new global::System.EventHandler (this.buttonClickedClear);
	}
}
